---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        types:
          - python
      - id: end-of-file-fixer
        types:
          - python
      - id: check-added-large-files
        types:
          - python
      - id: check-yaml
        types:
          - yaml
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
